# SPDX-License-Identifier: MIT
# A named conversion PCM keeps PortAudio away from the fixed-format hardware.
# PortAudio enumerates hardware through these parameterized interfaces.
ctl.hw {
    @args [ CARD ]
    @args.CARD { type string default "OpenH432" }
    type hw
    card $CARD
}
pcm.hw {
    @args [ CARD DEV ]
    @args.CARD { type string default "OpenH432" }
    @args.DEV { type integer default 0 }
    type hw
    card $CARD
    device $DEV
}
pcm.openh432_speech {
    type asym
    playback.pcm {
        type plug
        slave {
            pcm {
                type hw
                card OpenH432
                device 0
            }
            rate 44100
            channels 2
            format S16_LE
        }
    }
    hint {
        show on
        description "OpenH432 speech"
    }
}
pcm.!default {
    type plug
    slave.pcm "openh432_speech"
}
ctl.!default {
    type hw
    card OpenH432
}
