# SPDX-License-Identifier: MIT
# OpenH432 local appliance speech; no network listener or implicit synthesizer.
CommunicationMethod "unix_socket"
SocketPath "/run/fm-speech/speechd.sock"
LogLevel 1
LogDir "/run/fm-speech"
DisableAutoSpawn
AudioOutputMethod "alsa"
AudioALSADevice "openh432_speech"
AddModule "openevv" "sd_openevv" "/etc/openh432/speech/modules/openevv.conf"
DefaultModule openevv
DefaultLanguage en-US
DefaultVoiceType MALE1
DefaultRate 0
DefaultVolume 100
DefaultPunctuationMode "some"
SymbolsPreproc "no"
