# SPDX-License-Identifier: MIT
CommunicationMethod "unix_socket"
SocketPath "/run/fm-speech/speechd.sock"
LogLevel 2
LogDir "/run/fm-speech"
DisableAutoSpawn
AudioOutputMethod "alsa"
AudioALSADevice "openh432_speech"
AddModule "rhvoice" "sd_rhvoice"
DefaultModule "rhvoice"
DefaultLanguage "en"
DefaultVoiceType "FEMALE1"
DefaultRate 0
DefaultVolume 100
DefaultPunctuationMode "some"
SymbolsPreproc "no"
