# SPDX-License-Identifier: MIT
speech-driver sd
speech-parameters sd:Address=unix_socket:/run/fm-speech/speechd.sock,Autospawn=no,Module=openevv,Language=en-US,Voice=male1
preferences-file /etc/brltty.prefs
